name: Bug Report
description: Report a bug in the firewall application
title: "[Bug] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below to help us understand and fix the issue.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you using?
      placeholder: e.g., 0.0.1
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - Ubuntu
        - macOS
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug you encountered
      placeholder: |
        Steps to reproduce:
        1. Go to...
        2. Click on...
        3. See error...

        Expected behavior:
        What you expected to happen

        Actual behavior:
        What actually happened

        Error messages:
        Any error messages or screenshots
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Files
      description: Please attach any relevant log files (from logs/ directory)
      placeholder: Drag and drop log files here or paste relevant log content

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information that might help
      placeholder: |
        - Configuration settings
        - Firewall rules
        - System specifications
        - Other applications running
