blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/Nsfr750/firewall/discussions
    about: Ask general questions or start discussions
  - name: Feature Request
    url: https://github.com/Nsfr750/firewall/issues/new?template=feature_request.yml
    about: Suggest a new feature or enhancement
  - name: Bug Report
    url: https://github.com/Nsfr750/firewall/issues/new?template=bug_report.yml
    about: Report a bug or issue
